version: '2'
services:
  cms:
    build:
      context: ./docker-src/cms
    container_name: cms
    mem_limit: 512M
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - .:/var/www
    env_file: environment
    environment:
      - CONNECTBACK=on
    links:
      - db
      - memcache
      - elasticsearch
    networks:
      - connector
  db:
    image: mariadb:latest
    container_name: db
    mem_limit: 512M
    env_file: environment
    ports:
      - 3306:3306
    volumes:
      - ./docker-src/db/conf:/etc/mysql/conf.d
      - database:/var/lib/mysql
    networks:
      - connector
  memcache:
    image: memcached:latest
    container_name: memcached
    mem_limit: 128M
    environment:
      - MEMCACHED_SERVER=memcached:11211
    ports:
      - 11211:11211
    networks:
      - connector
  elasticsearch:
    build:
      context: ./docker-src/elasticsearch
    container_name: elasticsearch
    mem_limit: 2048M
    environment:
      - bootstrap.memory_lock:true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - connector
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

networks:
  connector:

volumes:
  database: {}
  elasticsearch: {}
