version: '3.4'
services:
  php:
    build:
      context: .
      dockerfile: ./docker-src/cms/Dockerfile
      target: php-dev
    image: ${IMAGE_MAINTAINER}/${PROJECT}-php
    container_name: ${PROJECT}-php
    env_file: environment
    environment:
      - CONNECTBACK=off
      - DRUPAL_MYSQL_HOST=${PROJECT}-db
    links:
      - db
      - memcache
    depends_on:
      - db
      - memcache
    networks:
      - connector
    volumes:
      - "./composer.json:/var/www/composer.json"
      - "./webroot:/var/www/webroot"
      - "./config:/var/www/config"
      - "./vendor:/var/www/vendor"
      - "./tests:/var/www/tests"

  web:
    build:
      context: .
      dockerfile: ./docker-src/cms/Dockerfile
      target: web-dev
    image: ${IMAGE_MAINTAINER}/${PROJECT}-web
    container_name: ${PROJECT}-web
    ports:
      - 8080:80
      - 8443:443
    networks:
      - connector
    links:
      - php
    depends_on:
      - php
    volumes:
      - "./webroot:/var/www/webroot:ro"

  db:
    image: mariadb:10
    container_name: ${PROJECT}-db
    env_file: environment
    volumes:
      - "./docker-src/db/conf:/etc/my.cnf.d"
      - "database:/var/lib/mysql"
    networks:
      - connector
    healthcheck:
      test: "mysqladmin ping -uroot -proot -hlocalhost"
      interval: 15s
      timeout: 5s
      retries: 5

  memcache:
    image: memcached:1.5-alpine
    container_name: ${PROJECT}-memcached
    environment:
      - MEMCACHED_SERVER=${PROJECT}-memcached:11211
    networks:
      - connector

networks:
  connector:

volumes:
  database: {}
