version: '3.4'
services:
  php:
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M

  web:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 64M

  db:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M

  memcache:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
