version: '3.4'
services:
  php:
    build:
      context: .
      dockerfile: ./docker-src/cms/Dockerfile
      target: php-$ENV
    image: ${IMAGE_MAINTAINER}/${PROJECT}-${ENV}-php
    env_file: environment
    environment:
      - CONNECTBACK=off
      - DRUPAL_MYSQL_HOST=${PROJECT}-${ENV}-db
    links:
      - db
      - memcache
    depends_on:
      - db
      - memcache
    networks:
      - connector
    volumes:
      - files:/var/www/drupal/sites/default/files

  web:
    build:
      context: .
      dockerfile: ./docker-src/cms/Dockerfile
      target: web-prod
    image: ${IMAGE_MAINTAINER}/${PROJECT}-${ENV}-web
    ports:
      - 8080:80
      - 8443:443
    networks:
      - connector
    links:
      - php
    depends_on:
      - php
    volumes:
      - files:/var/www/drupal/sites/default/files:ro

  db:
    build:
      context: ./docker-src/db
    image: ${IMAGE_MAINTAINER}/${PROJECT}-${ENV}-db
    container_name: ${PROJECT}-${ENV}-db
    env_file: environment
    volumes:
      - database:/var/lib/mysql
    networks:
      - connector
    healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       interval: 15s
       timeout: 5s
       retries: 5

  memcache:
    image: memcached:1.5-alpine
    container_name: ${PROJECT}-${ENV}-memcached
    environment:
      - MEMCACHED_SERVER=memcached-${PROJECT}:11211
    networks:
      - connector

networks:
  connector:

volumes:
  database: {}
  files: {}
