lint: # Check code for formatting or syntax errors
	docker exec -i php-${PROJECT} parallel-lint \
	  -e php,module,inc,install,test,profile,theme \
	  /var/www/drupal/modules/custom \
	  /var/www/drupal/themes/custom

sniff: # Description needed
	./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
	./vendor/bin/phpcs -n --standard=Drupal,DrupalPractice \
		--extensions=php,module,inc,install,test,profile,theme,info \
		--ignore=*/node_modules/* web/modules/custom web/themes/custom

code-test: lint sniff # Description needed

code-fix: # Description needed
	vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
	-vendor/bin/phpcbf --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,info web/modules/custom
	-vendor/bin/phpcbf --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,info --ignore=*/node_modules/* web/themes/custom
	#
shell: # This command will open a shell in the specified container as root. Usage: make shell <container type>
	docker exec -it --user root $(filter-out $@,$(MAKECMDGOALS))-${PROJECT} /bin/sh
