module:
  address: 0
  admin_toolbar: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contact_block: 0
  contact_storage: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  fontawesome: 0
  help: 0
  history: 0
  image: 0
  image_effects: 0
  kint: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  update: 0
  user: 0
  views_templates: 0
  views_ui: 0
  webprofiler: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  seven: 0
  classy: 0
  stable: 0
  bartik: 0
  uswds: 0
  goddard_uswds_sub: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
