definitions:
  block__admin_display:
    parent: system.admin_structure
    menu_name: admin
    enabled: true
    expanded: false
    weight: -63
  entity__comment_type__collection:
    weight: -62
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__contact_form__collection:
    weight: -61
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__node_type__collection:
    weight: -60
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  field_ui__display_mode:
    weight: -59
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__menu__collection:
    weight: -58
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__paragraphs_type__collection:
    weight: -57
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__taxonomy_vocabulary__collection:
    weight: -56
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__view__collection:
    weight: -55
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
