module:
  mysql: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  breakpoint: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  filter: 0
  help: 0
  node: 0
  page_cache: 0
  path_alias: 0
  system: 0
  text: 0
  toolbar: 0
  user: 0
  minimal: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  claro: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
