color_selector:
  plugin_id: html_color
  plugin_settings:
    html_color: {  }
image_selector:
  plugin_id: basic
  plugin_settings:
    basic: {  }
font_selector:
  plugin_id: basic
  plugin_settings:
    basic: {  }
_core:
  default_config_hash: eaXmaPSud65p-XhTwMIL9vKETD9zR3qNOMMa5EUuoNw
