country:
  default: US
first_day: 0
timezone:
  default: America/New_York
  user:
    configurable: true
    warn: true
    default: 0
_core:
  default_config_hash: V9UurX2GPT05NWKG9f2GWQqFG2TRG8vczidwjpy7Woo
